/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierRouteImport } from './routes/tier'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LfgRouteImport } from './routes/lfg'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TierIdRouteImport } from './routes/tier.$id'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as LfgIdRouteImport } from './routes/lfg.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DecksIdRouteImport } from './routes/decks.$id'
import { Route as CardsCodeRouteImport } from './routes/cards.$code'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as AdminSeedRouteImport } from './routes/admin.seed'
import { Route as AdminInspectRouteImport } from './routes/admin.inspect'
import { Route as AdminCardGeneratorRouteImport } from './routes/admin.card-generator'

const TierRoute = TierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LfgRoute = LfgRouteImport.update({
  id: '/lfg',
  path: '/lfg',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TierIdRoute = TierIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TierRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoresRoute,
} as any)
const LfgIdRoute = LfgIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LfgRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdRoute = DecksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecksRoute,
} as any)
const CardsCodeRoute = CardsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => CardsRoute,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInspectRoute = AdminInspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardGeneratorRoute = AdminCardGeneratorRouteImport.update({
  id: '/card-generator',
  path: '/card-generator',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cards': typeof CardsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/lfg': typeof LfgRouteWithChildren
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox': typeof SandboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/card-generator': typeof AdminCardGeneratorRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/seed': typeof AdminSeedRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cards': typeof CardsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/lfg': typeof LfgRouteWithChildren
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox': typeof SandboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/card-generator': typeof AdminCardGeneratorRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/seed': typeof AdminSeedRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cards': typeof CardsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/lfg': typeof LfgRouteWithChildren
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sandbox': typeof SandboxRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/card-generator': typeof AdminCardGeneratorRoute
  '/admin/inspect': typeof AdminInspectRoute
  '/admin/seed': typeof AdminSeedRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/cards'
    | '/collection'
    | '/decks'
    | '/leaderboard'
    | '/lfg'
    | '/login'
    | '/matches'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sandbox'
    | '/sitemap.xml'
    | '/stores'
    | '/tier'
    | '/admin/card-generator'
    | '/admin/inspect'
    | '/admin/seed'
    | '/announcements/$id'
    | '/api/coach'
    | '/cards/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/cards'
    | '/collection'
    | '/decks'
    | '/leaderboard'
    | '/lfg'
    | '/login'
    | '/matches'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sandbox'
    | '/sitemap.xml'
    | '/stores'
    | '/tier'
    | '/admin/card-generator'
    | '/admin/inspect'
    | '/admin/seed'
    | '/announcements/$id'
    | '/api/coach'
    | '/cards/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/cards'
    | '/collection'
    | '/decks'
    | '/leaderboard'
    | '/lfg'
    | '/login'
    | '/matches'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sandbox'
    | '/sitemap.xml'
    | '/stores'
    | '/tier'
    | '/admin/card-generator'
    | '/admin/inspect'
    | '/admin/seed'
    | '/announcements/$id'
    | '/api/coach'
    | '/cards/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CardsRoute: typeof CardsRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  DecksRoute: typeof DecksRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LfgRoute: typeof LfgRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  PacksRoute: typeof PacksRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SandboxRoute: typeof SandboxRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoresRoute: typeof StoresRouteWithChildren
  TierRoute: typeof TierRouteWithChildren
  ApiCoachRoute: typeof ApiCoachRoute
  EventsIdRoute: typeof EventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tier': {
      id: '/tier'
      path: '/tier'
      fullPath: '/tier'
      preLoaderRoute: typeof TierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lfg': {
      id: '/lfg'
      path: '/lfg'
      fullPath: '/lfg'
      preLoaderRoute: typeof LfgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier/$id': {
      id: '/tier/$id'
      path: '/$id'
      fullPath: '/tier/$id'
      preLoaderRoute: typeof TierIdRouteImport
      parentRoute: typeof TierRoute
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof StoresRoute
    }
    '/lfg/$id': {
      id: '/lfg/$id'
      path: '/$id'
      fullPath: '/lfg/$id'
      preLoaderRoute: typeof LfgIdRouteImport
      parentRoute: typeof LfgRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$id': {
      id: '/decks/$id'
      path: '/$id'
      fullPath: '/decks/$id'
      preLoaderRoute: typeof DecksIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/cards/$code': {
      id: '/cards/$code'
      path: '/$code'
      fullPath: '/cards/$code'
      preLoaderRoute: typeof CardsCodeRouteImport
      parentRoute: typeof CardsRoute
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inspect': {
      id: '/admin/inspect'
      path: '/inspect'
      fullPath: '/admin/inspect'
      preLoaderRoute: typeof AdminInspectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/card-generator': {
      id: '/admin/card-generator'
      path: '/card-generator'
      fullPath: '/admin/card-generator'
      preLoaderRoute: typeof AdminCardGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCardGeneratorRoute: typeof AdminCardGeneratorRoute
  AdminInspectRoute: typeof AdminInspectRoute
  AdminSeedRoute: typeof AdminSeedRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCardGeneratorRoute: AdminCardGeneratorRoute,
  AdminInspectRoute: AdminInspectRoute,
  AdminSeedRoute: AdminSeedRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface CardsRouteChildren {
  CardsCodeRoute: typeof CardsCodeRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCodeRoute: CardsCodeRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface DecksRouteChildren {
  DecksIdRoute: typeof DecksIdRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksIdRoute: DecksIdRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

interface LfgRouteChildren {
  LfgIdRoute: typeof LfgIdRoute
}

const LfgRouteChildren: LfgRouteChildren = {
  LfgIdRoute: LfgIdRoute,
}

const LfgRouteWithChildren = LfgRoute._addFileChildren(LfgRouteChildren)

interface StoresRouteChildren {
  StoresIdRoute: typeof StoresIdRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresIdRoute: StoresIdRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

interface TierRouteChildren {
  TierIdRoute: typeof TierIdRoute
}

const TierRouteChildren: TierRouteChildren = {
  TierIdRoute: TierIdRoute,
}

const TierRouteWithChildren = TierRoute._addFileChildren(TierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CardsRoute: CardsRouteWithChildren,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LfgRoute: LfgRouteWithChildren,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  PacksRoute: PacksRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SandboxRoute: SandboxRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoresRoute: StoresRouteWithChildren,
  TierRoute: TierRouteWithChildren,
  ApiCoachRoute: ApiCoachRoute,
  EventsIdRoute: EventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
