/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierRouteImport } from './routes/tier'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LfgIndexRouteImport } from './routes/lfg.index'
import { Route as DecksIndexRouteImport } from './routes/decks.index'
import { Route as CardsIndexRouteImport } from './routes/cards.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TierIdRouteImport } from './routes/tier.$id'
import { Route as StoresIdRouteImport } from './routes/stores.$id'
import { Route as LfgIdRouteImport } from './routes/lfg.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DecksIdRouteImport } from './routes/decks.$id'
import { Route as CardsCodeRouteImport } from './routes/cards_.$code'
import { Route as CardsUploadRouteImport } from './routes/cards.upload'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiCardOcrRouteImport } from './routes/api/card-ocr'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AuthGoogleDriveCallbackRouteImport } from './routes/auth.google-drive.callback'
import { Route as ApiDriveAuthRouteImport } from './routes/api.drive.auth'
import { Route as AdminCardsReviewRouteImport } from './routes/admin.cards.review'

const TierRoute = TierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LfgIndexRoute = LfgIndexRouteImport.update({
  id: '/lfg/',
  path: '/lfg/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksRoute,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CardsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TierIdRoute = TierIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TierRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StoresRoute,
} as any)
const LfgIdRoute = LfgIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LfgRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIdRoute = DecksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DecksRoute,
} as any)
const CardsCodeRoute = CardsCodeRouteImport.update({
  id: '/cards_/$code',
  path: '/cards/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsUploadRoute = CardsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => CardsRoute,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardOcrRoute = ApiCardOcrRouteImport.update({
  id: '/api/card-ocr',
  path: '/api/card-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/admin/cards',
  path: '/admin/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleDriveCallbackRoute = AuthGoogleDriveCallbackRouteImport.update({
  id: '/auth/google-drive/callback',
  path: '/auth/google-drive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveAuthRoute = ApiDriveAuthRouteImport.update({
  id: '/api/drive/auth',
  path: '/api/drive/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardsReviewRoute = AdminCardsReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminCardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cards': typeof CardsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/cards': typeof AdminCardsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/card-ocr': typeof ApiCardOcrRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/upload': typeof CardsUploadRoute
  '/cards/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/lfg/': typeof LfgIndexRoute
  '/admin/cards/review': typeof AdminCardsReviewRoute
  '/api/drive/auth': typeof ApiDriveAuthRoute
  '/auth/google-drive/callback': typeof AuthGoogleDriveCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/collection': typeof CollectionRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/cards': typeof AdminCardsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/card-ocr': typeof ApiCardOcrRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/upload': typeof CardsUploadRoute
  '/cards/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
  '/admin': typeof AdminIndexRoute
  '/cards': typeof CardsIndexRoute
  '/decks': typeof DecksIndexRoute
  '/lfg': typeof LfgIndexRoute
  '/admin/cards/review': typeof AdminCardsReviewRoute
  '/api/drive/auth': typeof ApiDriveAuthRoute
  '/auth/google-drive/callback': typeof AuthGoogleDriveCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/cards': typeof CardsRouteWithChildren
  '/collection': typeof CollectionRoute
  '/decks': typeof DecksRouteWithChildren
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/packs': typeof PacksRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/stores': typeof StoresRouteWithChildren
  '/tier': typeof TierRouteWithChildren
  '/admin/cards': typeof AdminCardsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/api/card-ocr': typeof ApiCardOcrRoute
  '/api/coach': typeof ApiCoachRoute
  '/cards/upload': typeof CardsUploadRoute
  '/cards_/$code': typeof CardsCodeRoute
  '/decks/$id': typeof DecksIdRoute
  '/events/$id': typeof EventsIdRoute
  '/lfg/$id': typeof LfgIdRoute
  '/stores/$id': typeof StoresIdRoute
  '/tier/$id': typeof TierIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/decks/': typeof DecksIndexRoute
  '/lfg/': typeof LfgIndexRoute
  '/admin/cards/review': typeof AdminCardsReviewRoute
  '/api/drive/auth': typeof ApiDriveAuthRoute
  '/auth/google-drive/callback': typeof AuthGoogleDriveCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/calendar'
    | '/cards'
    | '/collection'
    | '/decks'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/stores'
    | '/tier'
    | '/admin/cards'
    | '/admin/reports'
    | '/announcements/$id'
    | '/api/card-ocr'
    | '/api/coach'
    | '/cards/upload'
    | '/cards/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
    | '/admin/'
    | '/cards/'
    | '/decks/'
    | '/lfg/'
    | '/admin/cards/review'
    | '/api/drive/auth'
    | '/auth/google-drive/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/calendar'
    | '/collection'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/stores'
    | '/tier'
    | '/admin/cards'
    | '/admin/reports'
    | '/announcements/$id'
    | '/api/card-ocr'
    | '/api/coach'
    | '/cards/upload'
    | '/cards/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
    | '/admin'
    | '/cards'
    | '/decks'
    | '/lfg'
    | '/admin/cards/review'
    | '/api/drive/auth'
    | '/auth/google-drive/callback'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/calendar'
    | '/cards'
    | '/collection'
    | '/decks'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/packs'
    | '/profile'
    | '/reset-password'
    | '/sitemap.xml'
    | '/store'
    | '/stores'
    | '/tier'
    | '/admin/cards'
    | '/admin/reports'
    | '/announcements/$id'
    | '/api/card-ocr'
    | '/api/coach'
    | '/cards/upload'
    | '/cards_/$code'
    | '/decks/$id'
    | '/events/$id'
    | '/lfg/$id'
    | '/stores/$id'
    | '/tier/$id'
    | '/admin/'
    | '/cards/'
    | '/decks/'
    | '/lfg/'
    | '/admin/cards/review'
    | '/api/drive/auth'
    | '/auth/google-drive/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CardsRoute: typeof CardsRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  DecksRoute: typeof DecksRouteWithChildren
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MatchesRoute: typeof MatchesRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PacksRoute: typeof PacksRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  StoresRoute: typeof StoresRouteWithChildren
  TierRoute: typeof TierRouteWithChildren
  AdminCardsRoute: typeof AdminCardsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  ApiCardOcrRoute: typeof ApiCardOcrRoute
  ApiCoachRoute: typeof ApiCoachRoute
  CardsCodeRoute: typeof CardsCodeRoute
  EventsIdRoute: typeof EventsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LfgIndexRoute: typeof LfgIndexRoute
  ApiDriveAuthRoute: typeof ApiDriveAuthRoute
  AuthGoogleDriveCallbackRoute: typeof AuthGoogleDriveCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tier': {
      id: '/tier'
      path: '/tier'
      fullPath: '/tier'
      preLoaderRoute: typeof TierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lfg/': {
      id: '/lfg/'
      path: '/lfg'
      fullPath: '/lfg/'
      preLoaderRoute: typeof LfgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/'
      fullPath: '/decks/'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof DecksRoute
    }
    '/cards/': {
      id: '/cards/'
      path: '/'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof CardsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier/$id': {
      id: '/tier/$id'
      path: '/$id'
      fullPath: '/tier/$id'
      preLoaderRoute: typeof TierIdRouteImport
      parentRoute: typeof TierRoute
    }
    '/stores/$id': {
      id: '/stores/$id'
      path: '/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof StoresRoute
    }
    '/lfg/$id': {
      id: '/lfg/$id'
      path: '/$id'
      fullPath: '/lfg/$id'
      preLoaderRoute: typeof LfgIdRouteImport
      parentRoute: typeof LfgRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$id': {
      id: '/decks/$id'
      path: '/$id'
      fullPath: '/decks/$id'
      preLoaderRoute: typeof DecksIdRouteImport
      parentRoute: typeof DecksRoute
    }
    '/cards_/$code': {
      id: '/cards_/$code'
      path: '/cards/$code'
      fullPath: '/cards/$code'
      preLoaderRoute: typeof CardsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/upload': {
      id: '/cards/upload'
      path: '/upload'
      fullPath: '/cards/upload'
      preLoaderRoute: typeof CardsUploadRouteImport
      parentRoute: typeof CardsRoute
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card-ocr': {
      id: '/api/card-ocr'
      path: '/api/card-ocr'
      fullPath: '/api/card-ocr'
      preLoaderRoute: typeof ApiCardOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/admin/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google-drive/callback': {
      id: '/auth/google-drive/callback'
      path: '/auth/google-drive/callback'
      fullPath: '/auth/google-drive/callback'
      preLoaderRoute: typeof AuthGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/auth': {
      id: '/api/drive/auth'
      path: '/api/drive/auth'
      fullPath: '/api/drive/auth'
      preLoaderRoute: typeof ApiDriveAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cards/review': {
      id: '/admin/cards/review'
      path: '/review'
      fullPath: '/admin/cards/review'
      preLoaderRoute: typeof AdminCardsReviewRouteImport
      parentRoute: typeof AdminCardsRoute
    }
  }
}

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface CardsRouteChildren {
  CardsUploadRoute: typeof CardsUploadRoute
  CardsIndexRoute: typeof CardsIndexRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsUploadRoute: CardsUploadRoute,
  CardsIndexRoute: CardsIndexRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface DecksRouteChildren {
  DecksIdRoute: typeof DecksIdRoute
  DecksIndexRoute: typeof DecksIndexRoute
}

const DecksRouteChildren: DecksRouteChildren = {
  DecksIdRoute: DecksIdRoute,
  DecksIndexRoute: DecksIndexRoute,
}

const DecksRouteWithChildren = DecksRoute._addFileChildren(DecksRouteChildren)

interface StoresRouteChildren {
  StoresIdRoute: typeof StoresIdRoute
}

const StoresRouteChildren: StoresRouteChildren = {
  StoresIdRoute: StoresIdRoute,
}

const StoresRouteWithChildren =
  StoresRoute._addFileChildren(StoresRouteChildren)

interface TierRouteChildren {
  TierIdRoute: typeof TierIdRoute
}

const TierRouteChildren: TierRouteChildren = {
  TierIdRoute: TierIdRoute,
}

const TierRouteWithChildren = TierRoute._addFileChildren(TierRouteChildren)

interface AdminCardsRouteChildren {
  AdminCardsReviewRoute: typeof AdminCardsReviewRoute
}

const AdminCardsRouteChildren: AdminCardsRouteChildren = {
  AdminCardsReviewRoute: AdminCardsReviewRoute,
}

const AdminCardsRouteWithChildren = AdminCardsRoute._addFileChildren(
  AdminCardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CardsRoute: CardsRouteWithChildren,
  CollectionRoute: CollectionRoute,
  DecksRoute: DecksRouteWithChildren,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MatchesRoute: MatchesRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PacksRoute: PacksRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  StoresRoute: StoresRouteWithChildren,
  TierRoute: TierRouteWithChildren,
  AdminCardsRoute: AdminCardsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  ApiCardOcrRoute: ApiCardOcrRoute,
  ApiCoachRoute: ApiCoachRoute,
  CardsCodeRoute: CardsCodeRoute,
  EventsIdRoute: EventsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  LfgIndexRoute: LfgIndexRoute,
  ApiDriveAuthRoute: ApiDriveAuthRoute,
  AuthGoogleDriveCallbackRoute: AuthGoogleDriveCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
