-- 시뮬레이터 효과 적재 Phase 1C — 검증 완료 6장
-- 생성: scripts/build-effect-migration.ts (CardEffectsSchema 검증 통과분)
-- 지시서: docs/SIMULATOR_PHASE1_TASKS.md §1C
UPDATE cards SET effects = '[{"id":"on_play:izo_rest","label":"등장 시 상대 코스트4이하 레스트","trigger":"on_play","actions":[{"kind":"rest_target","count":1,"target":{"selector":"opponent_character_filter","filter":{"cost_max":4}}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP01-033';
UPDATE cards SET effects = '[{"id":"on_play:otama_debuff","label":"등장 시 파워 -2000","trigger":"on_play","actions":[{"kind":"power_modifier","delta":-2000,"duration":"this_turn","scope":"single","target":{"selector":"opponent_character_filter","filter":{}}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP01-006';
UPDATE cards SET effects = '[{"id":"main:exorcism_ko","label":"레스트 코스트5이하 2장 KO","trigger":"main","actions":[{"kind":"ko_target","count":2,"target":{"selector":"opponent_character_filter","filter":{"cost_max":5,"rested_only":true}}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP01-056';
UPDATE cards SET effects = '[{"id":"on_play:nojiko_bounce","label":"나미 리더 시 코스트5이하 바운스","trigger":"on_play","conditions":[{"kind":"self_leader_name_is","value":"나미"}],"actions":[{"kind":"return_to_hand","count":1,"target":{"selector":"opponent_character_filter","filter":{"cost_max":5}}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP03-048';
UPDATE cards SET effects = '[{"id":"counter:web_4000","label":"카운터 파워 +4000","trigger":"counter","actions":[{"kind":"power_modifier","delta":4000,"duration":"this_battle","scope":"single","target":{"selector":"self_leader"}},{"kind":"active_target","count":1,"target":{"selector":"self_character_any"}}]},{"id":"trigger:web_2000","label":"트리거 리더 +2000","trigger":"on_trigger","actions":[{"kind":"power_modifier","delta":2000,"duration":"this_turn","scope":"single","target":{"selector":"self_leader"}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP04-035';
UPDATE cards SET effects = '[{"id":"activate:luffy_active_buff","label":"기동 액티브 + 파워 +1000","trigger":"activate_main","cost":{"don_rest":4},"actions":[{"kind":"active_target","count":1,"target":{"selector":"self_character_filter","filter":{"cost_max":5,"trait":["초신성","밀짚모자 일당"]}}},{"kind":"power_modifier","delta":1000,"duration":"this_turn","scope":"single","target":{"selector":"self_character_filter","filter":{"cost_max":5,"trait":["초신성","밀짚모자 일당"]}}}]}]'::jsonb WHERE game = 'optcg' AND code = 'OP01-003';
